task:
  name: LLVM Toolchain
  timeout_in: 120m
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Deploy-builder_script: |
        bash build_clang.sh && bash build_binutils.sh
